### ISSUE TITLE
Will this work without linear rails??

### ISSUE THREAD

**Issue by BigBadAl-maker** [yohannaftali/Marlin-Firmware-BTT-SKR-Mini-Hemera#2]
What changes are needed for using stock rails please.

Apart from that, is it ready to compile?

(I'm a total noob at this, building my first Frankenstein printer and only ever used complied BIN files before)

Thanks.

**Comment by yohannaftali** [comment]
If you change and use linear rail,  you have to adjust some variable in configuration.h
1. NOZZLE_TO_PROBE_OFFSET, please measure in mm probe and nozzle distance - Line 1036 (because you use different mount)
2. #define MANUAL_X_HOME_POS (mine is -18 mm)
3. #define MANUAL_Y_HOME_POS (mine is -19 mm)
4. #define Y_BED_SIZE (mine became 211 // 235 - MANUAL_Y_HOME_POS - 5 = 235-19-5) - Line 1175 

Also GCode in end printing if you use cura, when presenting use Y max to bed size (default 220 will make your printer stuck)
configuration.h https://github.com/yohannaftali/Marlin-Firmware-BTT-SKR-Mini-Hemera/blob/main/Marlin-bugfix-2.0.x/Marlin/Configuration.h
